export const FooterList = [
  { name: "Meta" },
  { name: "소개" },
  { name: "블로그" },
  { name: "채용 정보" },
  { name: "도움말" },
  { name: "API" },
  { name: "개인정보처리방침" },
  { name: "약관" },
  { name: "인기 계정" },
  { name: "위치" },
  { name: "Instagram Lite" },
  { name: "Threads" },
  { name: "연락처 업로드 & 비사용자" },
  { name: "Meta Verified" },
];
